title: Blake Davies V3.0
url: https://master--blakedaviesnet-v3.netlify.com/
twitter:
markdown: kramdown
plugins_dir: _plugins
layouts_dir: _layouts
includes_dir: _includes
sass:
    sass_dir: assets/css/_sass
    style: expanded